Task 1: Basic OOP
Buatlah class MarketingDataETL yang memiliki tiga metode:

extract(): akan membaca data dari sebuah file CSV (Misalkan, marketing_data.csv)

transform(): akan melakukan pembersihan dan transformasi sederhana pada data (seperti mengubah format tanggal atau membersihkan nilai yang kosong)

store(): akan menyimpan data yang telah ditransformasi ke dalam struktur data DataFramet.

In [ ]:
import pandas as pd

class MarketingDataETL:
    def __init__(self, file_path):
        self.file_path = file_path
        self.data = None

    def extract(self):
        try:
            self.data = pd.read_csv(self.file_path, sep=';')
            print("Data berhasil diekstraksi.")
        except Exception as e:
            print("Terjadi kesalahan saat ekstraksi data:", str(e))

    def transform(self):
        if self.data is not None:
            if 'purchase_date' in self.data.columns:
                self.data['purchase_date'] = pd.to_datetime(self.data['purchase_date'], errors='coerce')
            self.data.dropna(inplace=True)
            print("Transformasi data berhasil.")
        else:
            print("Tidak ada data untuk dilakukan transformasi.")

    def store(self, output_file):
        if self.data is not None:
            try:
                self.data.to_csv(output_file, index=False)
                print("Data berhasil disimpan ke", output_file)
            except Exception as e:
                print("Terjadi kesalahan saat penyimpanan data:", str(e))
        else:
            print("Tidak ada data untuk disimpan.")

In [ ]:
#contoh
if __name__ == "__main__":
    etl = MarketingDataETL("marketing_data.csv")
    etl.extract()
    etl.transform()
    etl.store("transformed_marketing_data.csv")

Terjadi kesalahan saat ekstraksi data: [Errno 2] No such file or directory: 'marketing_data.csv'
Tidak ada data untuk dilakukan transformasi.
Tidak ada data untuk disimpan.

In [ ]:
transformed = pd.read_csv("transformed_marketing_data.csv")
transformed

  customer_id purchase_date product_category  amount_spent
0        C001    2023-01-03      Electronics        250.00
1        C002    2023-02-03            Books         45.50
2        C003    2023-03-03    Home & Garden        150.75
3        C001    2023-04-03            Books         20.00
4        C002    2023-05-03      Electronics        525.00
5        C005    2023-07-03           Beauty         75.00

taks 2
Gunakan inheritance untuk membuat class TargetedMarketingETL yang mewarisi dari MarketingDataETL.

Tambahkan metode segment_customers() yang mengelompokkan pelanggan berdasarkan kriteria tertentu (misalnya, pengeluaran total atau kategori produk yang dibeli).

Demonstrasi polymorphism dengan meng-override metode transform() dalam TargetedMarketingETL untuk menambahkan logika segmentasi pelanggan ke dalam proses transformasi.

In [ ]:
class TargetedMarketingETL(MarketingDataETL):
    def segment_customers(self, criteria):
        if self.data is not None:
            if criteria == 'total_spent':
                segments = self.data.groupby('customer_id')['amount_spent'].sum()
                print("Segmentasi pelanggan berdasarkan total pengeluaran:")
                print(segments)
            elif criteria == 'product_category':
                segments = self.data.groupby('customer_id')['product_category'].unique()
                print("Segmentasi pelanggan berdasarkan kategori produk yang dibeli:")
                print(segments)
            else:
                print("Kriteria segmentasi tidak valid.")
        else:
            print("Tidak ada data untuk dilakukan segmentasi.")

    def transform(self):
        super().transform()  # Memanggil metode transform() dari kelas induk
        # Logika tambahan untuk segmentasi pelanggan
        print("Proses segmentasi pelanggan telah selesai.")

In [ ]:
# Contoh penggunaan:
if __name__ == "__main__":
    targeted_etl = TargetedMarketingETL("marketing_data.csv")
    targeted_etl.extract()
    targeted_etl.transform()
    targeted_etl.segment_customers('product_category')

Data berhasil diekstraksi.
Transformasi data berhasil.
Proses segmentasi pelanggan telah selesai.
Segmentasi pelanggan berdasarkan kategori produk yang dibeli:
customer_id
C001    [Electronics, Books]
C002    [Books, Electronics]
C003         [Home & Garden]
C005                [Beauty]
Name: product_category, dtype: object